services:
  node-local-uno:
    hostname: local-app
    image: node-unir-uno:latest
    ports:
      - 3000:3000
    entrypoint: ["pm2-runtime", "/app/hello.js", "-i", "max"]
    restart: always
    networks:
          unir:
            aliases:
              - local-app.unir

  nginx-local-uno:
    hostname: local-proxy
    image: nginx-unir-uno:latest
    restart: always
    ports:
      - 80:80
    volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
          unir:
            aliases:
              - local-proxy.unir

networks:
  unir:
    driver: bridge
    name: unir